<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Data Customers</h3>
            </div><!-- /.box-header -->
            <div class="box-body">
                <table id="tbl-customers" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Customer ID</th>
                            <th>Customer Name</th>
                            <th>Address</th>
                            <th>Email</th>
                            <th>Contact Person</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($tabel_data as $idx => $data) {
                            echo '
                                <tr>
                                    <td>'.$data['id'].'</td>
                                    <td>'.$data['name'].'</td>
                                    <td>'.$data['address'].'</td>
                                    <td>'.$data['email'].'</td>
                                    <td>'.$data['contact_person'].'</td>
                                    <td>
                                        <button class="btn btn-warning btn-xs btn-edit" data-idx="'.$idx.'"><i class="fa fa-edit"></i> Edit</button>
                                        <button class="btn btn-danger btn-xs btn-delete" data-idx="'.$idx.'"><i class="fa fa-trash"></i> Delete</button>
                                    </td>
                                </tr>
                            ';
                        }
                        ?>
                    </tbody>
                </table>
                <button class="btn btn-success" id="btn-add"> <i class="fa fa-plus"></i> Add</button>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

<div class="modal fade" id="mdl-tambah" tabindex="-1" role="dialog" aria-labelledby="mdl-tambah" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h2 class="modal-title">Master Customer</h2>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="form-customer" action="<?= base_url('customer/save') ?>" method="POST">
                    <div class="form-group">
                        <label for="cust-id" class="col-sm-4 control-label">Customer ID</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" readonly="" id="cust-id" placeholder="Generated by system" name="id">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cust-name" class="col-sm-4 control-label">Customer Name</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="cust-name" placeholder="Nama Customer" name="name" required="" maxlength="50">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cust-pass" class="col-sm-4 control-label">Password</label>
                        <div class="col-sm-8">
                            <input type="password" class="form-control" id="cust-pass" placeholder="Password" name="password" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-4 control-label">Address</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="cust-addr" placeholder="Alamat" name="address" required="" maxlength="150">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cust-email" class="col-sm-4 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" id="cust-email" placeholder="customer@email.com" name="email" required="" maxlength="50">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cust-telp" class="col-sm-4 control-label">Telephone</label>
                        <div class="col-sm-8">
                            <input type="tel" class="form-control" id="cust-telp" placeholder="telp" name="No telp" required="" maxlength="15">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cust-cp" class="col-sm-4 control-label">Contact Person</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="cust-cp" placeholder="Custemer Contact" name="contact_person" required="" maxlength="50">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-8">
                            <button type="submit" class="btn btn-default">Save</button>
                            <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="mdl-hapus" tabindex="-1" role="dialog" aria-labelledby="mdl-hapus" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h2 class="modal-title">Confirm</h2>
            </div>
            <div class="modal-body">
                Are you sure to delete this customer?
            </div>
            <div class="modal-footer">
                <form action="<?= base_url('customer/delete') ?>" method="POST">
                    <input type="hidden" id="id-delete" name="id"/>
                    <button class="btn btn-danger" type="submit">Yes</button>
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src='<?= base_url('assets/js/common.js'); ?>'></script>
<script type="text/javascript">
    TABEL.data = <?= json_encode($tabel_data); ?>;
    $(function () {
        $("#tbl-customers").DataTable();
        
        $("#tbl-customers").on('submit', function(){
            
        });
        
        $('.btn-delete').on('click', function () {
            var id = $(this).attr('data-idx');
            TABEL.pilihan = TABEL.data[id];
            $('#id-delete').val(TABEL.pilihan.id);
            $('#mdl-hapus').modal('show');
        });
                
        $('.btn-edit').on('click', function () {
            var id = $(this).attr('data-idx');
            TABEL.pilihan = TABEL.data[id];
            
            $('#cust-id').val(TABEL.pilihan.id);
            $('#cust-name').val(TABEL.pilihan.name);
            $('#cust-pass').val();
            $('#cust-addr').val(TABEL.pilihan.address);
            $('#cust-email').val(TABEL.pilihan.email);
            $('#cust-telp').val(TABEL.pilihan.telp);
            $('#cust-cp').val(TABEL.pilihan.contact_person);
            
            $('#mdl-tambah').modal('show');
        });
        
        $('#btn-add').on('click', function () {
            $('#mdl-tambah').modal('show');
        });

    });
</script>
