<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h2 class="box-title">Daftar Employee</h2>
            </div><!-- /.box-header -->
            <div class="box-body">
                <table id="tbl-customers" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Employee ID</th>
                            <th>Employee Name</th>
                            <th>Email</th>
                            <th>Group</th>
                            <th>Telephone</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
//                        foreach ($tabel_data as $data) {
//                            echo '
//                                <tr>
//                                    <td>'. $data['id'] .'</td>
//                                    <td>'. $data['name'] .'</td>
//                                    <td>'. $data['email'] .'</td>
//                                    <td>'. $data['group'] .'</td>
//                                    <td>'. $data['telp'] .'</td>
//                                    <td>
//                                        <button class="btn btn-warning btn-xs btn-edit"><i class="fa fa-edit"></i> Edit</button>
//                                        <button class="btn btn-danger btn-xs btn-delete"><i class="fa fa-trash"></i> Delete</button>
//                                    </td>
//                                </tr>
//                            ';
//                        }
                        ?>
                    </tbody>
                </table>
                <button class="btn btn-success" id="btn-add"> <i class="fa fa-plus"></i> Add</button>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

<div class="modal fade" id="mdl-tambah" tabindex="-1" role="dialog" aria-labelledby="mdl-tambah" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h2 class="modal-title">Master Employee</h2>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" id="form-employee" action="<?= base_url('employee/baru') ?>" method="POST">
                    <div class="form-group">
                        <label for="empl_id" class="col-sm-3 control-label">Employee ID</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="empl-id" name="empl-id" readonly="" placeholder="Generated by system">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="empl-name" class="col-sm-3 control-label">Employee Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" id="empl-name" name="empl-name" placeholder="Nama" required="" maxlength="50">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="empl-paswd" class="col-sm-3 control-label">Password</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control" id="empl-paswd" name="empl-paswd" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="cust-name" class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-9">
                            <input type="email" class="form-control" id="empl-email" name="empl-email" placeholder="employee@email.com" required="" maxlength="50">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-3 control-label">Group</label>
                        <div class="col-sm-9">
                            <select class="form-control" name="empl-group" id="empl-group" required="">
                                <?php
                                foreach ($group_list as $group) {
                                    echo "<option value='" . $group['group_code'] . "'>" .$group['group_code']."-". $group['group_name'] . "</option>";
                                }
                                ?>
                            </select>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-3 control-label">Telephone</label>
                        <div class="col-sm-9">
                            <input type="tel" class="form-control" id="empl-telp" placeholder="0858989" required="" name="empl-telp" maxlength="15">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <button type="submit" class="btn btn-default" id="btn-save-empl">Save</button>
                            <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="mdl-hapus" tabindex="-1" role="dialog" aria-labelledby="mdl-hapus" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h2 class="modal-title">Confirm</h2>
            </div>
            <div class="modal-body">
                Are you sure to delete this item?
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" id="btn-hapus-data">Yes</button>
                <button class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<script src='<?= base_url('assets/js/common.js'); ?>'></script>
<script type="text/javascript">
    $(function () {
//        table = $("#tbl-customers").DataTable();

        TABEL.name = "#tbl-customers";
        TABEL.data = <?= json_encode($tabel_data); ?>;
        TABEL.kolom = [
            {data: 'id'},
            {data: 'name'},
            {data: 'email'},
            {data: 'group'},
            {data: 'telp'},
            {
                data: 'id', render: function (id) {
                    var el = '<button class="btn btn-warning btn-xs btn-edit"><i class="fa fa-edit"></i> Edit</button>' +
                            ' <button class="btn btn-danger btn-xs btn-delete"><i class="fa fa-trash"></i> Delete</button>';
                    return el;
                }
            }
        ];
        TABEL.inisiasi();

        $('#btn-add').on('click', function () {
            $('#form-employee')[0].reset();
            $('#mdl-tambah').modal('show');
        });

//        $('.btn-edit').on('click', function () {
        $(document).on('click', '.btn-edit', function () {

//            pilihan = table.row($(this).parents('tr')).data();
            TABEL.pilihan = TABEL.obj.row($(this).parents('tr')).data();
            $('#empl-id').val(TABEL.pilihan.id);
            $('#empl-name').val(TABEL.pilihan.name);
            $('#empl-paswd').val();
            $('#empl-email').val(TABEL.pilihan.email);
            $('#empl-group').val(TABEL.pilihan.group);
            $('#empl-telp').val(TABEL.pilihan.telp);

            $('#mdl-tambah').modal('show');
        });

        $('.btn-delete').on('click', function () {
            TABEL.pilihan = TABEL.obj.row($(this).parents('tr')).data();
            $('#mdl-hapus').modal('show');
        });

        $('#btn-hapus-data').on('click', function () {
            TABEL.api = "employee_hapus";
            TABEL.hapus();
            $('#mdl-hapus').modal('hide');
        });

        $('#form-employee').on('submit', function (e) {
            e.preventDefault();
            console.log('onSubmit');
            $('#mdl-tambah').modal('hide');
            newEmpl = {
                id: $('#empl-id').val(),
                name: $('#empl-name').val(),
                paswd: $('#empl-paswd').val(),
                email: $('#empl-email').val(),
                group: $('#empl-group').val(),
                telp: $('#empl-telp').val()
            };

            TABEL.newRow = newEmpl;
            TABEL.api = "employee_baru";

            if (!TABEL.newRow.id) {
                TABEL.aksi = 'tambah';
            } else {
                TABEL.aksi = 'ubah';
            }

            TABEL.tambah();

            console.log("berhenti");
        });

    });
</script>
